// packages/react/src/components/ui/HyperlinkPopup.tsx
/**
 * HyperlinkPopup Component
 *
 * Google Docs-style floating popup that appears when clicking on a hyperlink.
 * View mode: shows URL, copy, edit, and unlink buttons.
 * Edit mode: shows text + URL inputs with Apply button.
 */

import React, { useState, useEffect, useRef, useCallback } from 'react';
import type { CSSProperties } from 'react';
import { toast } from 'sonner';
import { useTranslation } from '../../i18n';

// ============================================================================
// TYPES
// ============================================================================

export interface HyperlinkPopupData {
  /** The hyperlink URL */
  href: string;
  /** Display text of the hyperlink */
  displayText: string;
  /** Tooltip if any */
  tooltip?: string;
  /** Popup position in the PagedEditor root container's coordinate space
   *  (CSS pixels from its top-left). Computed once at click time. The
   *  popup renders with `position: absolute` inside that container, so the
   *  browser handles repositioning during scroll for free. */
  position: { top: number; left: number };
}

export interface HyperlinkPopupProps {
  /** Popup data (null = hidden) */
  data: HyperlinkPopupData | null;
  /** Called when user wants to navigate to the link */
  onNavigate: (href: string) => void;
  /** Called when user wants to copy the URL */
  onCopy: (href: string) => void;
  /** Called when user saves edits (text, url) */
  onEdit: (displayText: string, href: string) => void;
  /** Called when user unlinks */
  onRemove: () => void;
  /** Called when popup should close */
  onClose: () => void;
  /** Whether the editor is read-only */
  readOnly?: boolean;
}

// ============================================================================
// STYLES
// ============================================================================

const BASE_POPUP_STYLE: CSSProperties = {
  position: 'absolute',
  zIndex: 10000,
  background: 'white',
  borderRadius: '8px',
  boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 4px 12px rgba(0,0,0,0.08)',
  border: '1px solid #dadce0',
  fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  fontSize: '14px',
};

const POPUP_STYLE: CSSProperties = {
  ...BASE_POPUP_STYLE,
  padding: '8px 12px',
  display: 'flex',
  alignItems: 'center',
  gap: '8px',
  maxWidth: '400px',
};

const EDIT_POPUP_STYLE: CSSProperties = {
  ...BASE_POPUP_STYLE,
  padding: '12px',
  width: '320px',
};

const ICON_STYLE: CSSProperties = {
  width: '20px',
  height: '20px',
  flexShrink: 0,
  color: '#5f6368',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
};

const URL_LINK_STYLE: CSSProperties = {
  color: '#1a73e8',
  textDecoration: 'none',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap',
  maxWidth: '220px',
  fontSize: '14px',
  lineHeight: '20px',
  cursor: 'pointer',
};

const ICON_BUTTON_STYLE: CSSProperties = {
  width: '28px',
  height: '28px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  border: 'none',
  background: 'none',
  borderRadius: '4px',
  cursor: 'pointer',
  color: '#5f6368',
  padding: 0,
  flexShrink: 0,
};

const SEPARATOR_STYLE: CSSProperties = {
  width: '1px',
  height: '20px',
  background: '#dadce0',
  flexShrink: 0,
};

const EDIT_ROW_STYLE: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '8px',
  marginBottom: '8px',
};

const EDIT_INPUT_STYLE: CSSProperties = {
  flex: 1,
  padding: '6px 8px',
  border: '1px solid #dadce0',
  borderRadius: '4px',
  fontSize: '14px',
  outline: 'none',
  lineHeight: '20px',
};

const APPLY_BUTTON_STYLE: CSSProperties = {
  color: '#1a73e8',
  fontWeight: 600,
  fontSize: '14px',
  border: 'none',
  background: 'none',
  cursor: 'pointer',
  padding: '6px 12px',
  borderRadius: '4px',
  flexShrink: 0,
};

// ============================================================================
// SVG ICONS
// ============================================================================

const SVG_PROPS = {
  width: 18,
  height: 18,
  viewBox: '0 0 24 24',
  fill: 'none',
  stroke: 'currentColor',
  strokeWidth: 2,
  strokeLinecap: 'round' as const,
  strokeLinejoin: 'round' as const,
};

function GlobeIcon() {
  return (
    <svg {...SVG_PROPS}>
      <circle cx="12" cy="12" r="10" />
      <path d="M2 12h20" />
      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>
  );
}

function CopyIcon() {
  return (
    <svg {...SVG_PROPS}>
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function EditIcon() {
  return (
    <svg {...SVG_PROPS}>
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z" />
    </svg>
  );
}

function UnlinkIcon() {
  return (
    <svg {...SVG_PROPS}>
      <path d="M18.84 12.25l1.72-1.71h-.02a5.004 5.004 0 0 0-.12-7.07 5.006 5.006 0 0 0-6.95 0l-1.72 1.71" />
      <path d="M5.17 11.75l-1.71 1.71a5.004 5.004 0 0 0 .12 7.07 5.006 5.006 0 0 0 6.95 0l1.71-1.71" />
      <line x1="8" y1="2" x2="8" y2="5" />
      <line x1="2" y1="8" x2="5" y2="8" />
      <line x1="16" y1="19" x2="16" y2="22" />
      <line x1="19" y1="16" x2="22" y2="16" />
    </svg>
  );
}

function TextIcon() {
  return (
    <svg {...SVG_PROPS}>
      <line x1="4" y1="9" x2="20" y2="9" />
      <line x1="4" y1="15" x2="20" y2="15" />
      <line x1="10" y1="3" x2="8" y2="21" />
      <line x1="16" y1="3" x2="14" y2="21" />
    </svg>
  );
}

function LinkIcon() {
  return (
    <svg {...SVG_PROPS}>
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  );
}

// ============================================================================
// ICON BUTTON HELPER
// ============================================================================

function PopupIconButton({
  title,
  onClick,
  children,
}: {
  title: string;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      className="ep-hyperlink-popup__icon-btn"
      style={ICON_BUTTON_STYLE}
      title={title}
      onClick={onClick}
    >
      {children}
    </button>
  );
}

// ============================================================================
// COMPONENT
// ============================================================================

export function HyperlinkPopup({
  data,
  onNavigate,
  onCopy,
  onEdit,
  onRemove,
  onClose,
  readOnly,
}: HyperlinkPopupProps): React.ReactElement | null {
  const { t } = useTranslation();
  const [mode, setMode] = useState<'view' | 'edit'>('view');
  const [editText, setEditText] = useState('');
  const [editUrl, setEditUrl] = useState('');
  const popupRef = useRef<HTMLDivElement>(null);
  const textInputRef = useRef<HTMLInputElement>(null);

  // Reset state when data changes
  useEffect(() => {
    if (data) {
      setMode('view');
      setEditText(data.displayText);
      setEditUrl(data.href);
    }
  }, [data]);

  // Focus text input when entering edit mode
  useEffect(() => {
    if (mode === 'edit') {
      requestAnimationFrame(() => {
        textInputRef.current?.focus();
        textInputRef.current?.select();
      });
    }
  }, [mode]);

  // Close on outside click
  useEffect(() => {
    if (!data) return;

    let aborted = false;
    const handleMouseDown = (e: MouseEvent) => {
      if (popupRef.current && !popupRef.current.contains(e.target as Node)) {
        onClose();
      }
    };

    // Defer so the click that opened the popup doesn't immediately close it
    const timer = setTimeout(() => {
      if (!aborted) document.addEventListener('mousedown', handleMouseDown);
    }, 0);

    return () => {
      aborted = true;
      clearTimeout(timer);
      document.removeEventListener('mousedown', handleMouseDown);
    };
  }, [data, onClose]);

  // Close on Escape
  useEffect(() => {
    if (!data) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (mode === 'edit') {
          setMode('view');
        } else {
          onClose();
        }
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [data, mode, onClose]);

  const handleCopy = useCallback(() => {
    if (!data) return;
    onCopy(data.href);
    toast('Link copied to clipboard');
  }, [data, onCopy]);

  const handleEditClick = useCallback(() => {
    if (!data) return;
    // Reset fields in case user previously edited and pressed Escape
    setEditText(data.displayText);
    setEditUrl(data.href);
    setMode('edit');
  }, [data]);

  const handleApply = useCallback(() => {
    const trimmedUrl = editUrl.trim();
    if (!trimmedUrl) return;
    onEdit(editText.trim() || trimmedUrl, trimmedUrl);
  }, [editText, editUrl, onEdit]);

  const handleEditKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === 'Enter') {
        e.preventDefault();
        handleApply();
      }
    },
    [handleApply]
  );

  if (!data) return null;

  // Position is in PagedEditor container coords; popup is rendered inside
  // that container so the browser repositions it on scroll automatically.
  const popupTop = data.position.top;
  const popupLeft = data.position.left;

  if (mode === 'edit') {
    return (
      <div
        ref={popupRef}
        className="ep-hyperlink-popup ep-hyperlink-popup--edit"
        style={{
          ...EDIT_POPUP_STYLE,
          top: popupTop,
          left: popupLeft,
        }}
        onMouseDown={(e) => e.stopPropagation()}
      >
        {/* Text field */}
        <div style={EDIT_ROW_STYLE}>
          <span style={ICON_STYLE}>
            <TextIcon />
          </span>
          <input
            ref={textInputRef}
            type="text"
            style={EDIT_INPUT_STYLE}
            value={editText}
            onChange={(e) => setEditText(e.target.value)}
            onKeyDown={handleEditKeyDown}
            placeholder={t('hyperlinkPopup.displayTextPlaceholder')}
            onFocus={(e) => (e.target.style.borderColor = '#1a73e8')}
            onBlur={(e) => (e.target.style.borderColor = '#dadce0')}
          />
        </div>

        {/* URL field + Apply */}
        <div style={{ ...EDIT_ROW_STYLE, marginBottom: 0 }}>
          <span style={ICON_STYLE}>
            <LinkIcon />
          </span>
          <input
            type="text"
            style={EDIT_INPUT_STYLE}
            value={editUrl}
            onChange={(e) => setEditUrl(e.target.value)}
            onKeyDown={handleEditKeyDown}
            placeholder={t('hyperlinkPopup.urlPlaceholder')}
            onFocus={(e) => (e.target.style.borderColor = '#1a73e8')}
            onBlur={(e) => (e.target.style.borderColor = '#dadce0')}
          />
          <button
            type="button"
            style={{
              ...APPLY_BUTTON_STYLE,
              opacity: editUrl.trim() ? 1 : 0.5,
              cursor: editUrl.trim() ? 'pointer' : 'default',
            }}
            onClick={handleApply}
            disabled={!editUrl.trim()}
          >
            {t('common.apply')}
          </button>
        </div>
      </div>
    );
  }

  // View mode
  return (
    <div
      ref={popupRef}
      className="ep-hyperlink-popup"
      style={{
        ...POPUP_STYLE,
        top: popupTop,
        left: popupLeft,
      }}
      onMouseDown={(e) => e.stopPropagation()}
    >
      {/* Globe icon */}
      <span style={ICON_STYLE}>
        <GlobeIcon />
      </span>

      {/* Clickable URL */}
      <a
        href={data.href}
        style={URL_LINK_STYLE}
        title={data.href}
        target="_blank"
        rel="noopener noreferrer"
        onClick={(e) => {
          e.preventDefault();
          onNavigate(data.href);
        }}
      >
        {data.href}
      </a>

      <span style={SEPARATOR_STYLE} />

      {/* Copy button */}
      <PopupIconButton title={t('hyperlinkPopup.copyLink')} onClick={handleCopy}>
        <CopyIcon />
      </PopupIconButton>

      {!readOnly && (
        <>
          <PopupIconButton title={t('hyperlinkPopup.editLink')} onClick={handleEditClick}>
            <EditIcon />
          </PopupIconButton>

          <PopupIconButton title={t('hyperlinkPopup.removeLink')} onClick={onRemove}>
            <UnlinkIcon />
          </PopupIconButton>
        </>
      )}
    </div>
  );
}

export default HyperlinkPopup;

// packages/vue/src/components/ui/HyperlinkPopup.vue
<!--
  Vue port of packages/react/src/components/ui/HyperlinkPopup.tsx —
  Floating popup for hyperlinks. View mode shows
  URL + copy / edit / unlink buttons; edit mode shows text + URL
  inputs + Apply button. Same colour palette + same anchor
  positioning as React.
-->
<template>
  <div
    v-if="data"
    ref="popupRef"
    :class="['docx-hyperlink-popup', { 'docx-hyperlink-popup--edit': isEditing }]"
    :style="popupStyle"
    @mousedown.stop
  >
    <template v-if="!isEditing">
      <span class="docx-hyperlink-popup__icon" aria-hidden>
        <svg
          width="18"
          height="18"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <circle cx="12" cy="12" r="10" />
          <path d="M2 12h20" />
          <path
            d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"
          />
        </svg>
      </span>
      <a
        class="docx-hyperlink-popup__url"
        :href="data.href"
        :title="data.href"
        @click.prevent="$emit('navigate', data.href)"
      >
        {{ data.href }}
      </a>
      <span class="docx-hyperlink-popup__sep" />
      <button
        class="docx-hyperlink-popup__btn"
        :title="t('hyperlinkPopup.copyLink')"
        @click.prevent="onCopy"
      >
        <svg
          width="18"
          height="18"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
          <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
        </svg>
      </button>
      <button
        v-if="!readOnly"
        class="docx-hyperlink-popup__btn"
        :title="t('hyperlinkPopup.editLink')"
        @click.prevent="startEdit"
      >
        <svg
          width="18"
          height="18"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
          <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
        </svg>
      </button>
      <button
        v-if="!readOnly"
        class="docx-hyperlink-popup__btn"
        :title="t('hyperlinkPopup.removeLink')"
        @click.prevent="$emit('remove')"
      >
        <svg
          width="18"
          height="18"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path
            d="M18.84 12.25l1.72-1.71h-.02a5.004 5.004 0 0 0-.12-7.07 5.006 5.006 0 0 0-6.95 0l-1.72 1.71"
          />
          <path
            d="M5.17 11.75l-1.71 1.71a5.004 5.004 0 0 0 .12 7.07 5.006 5.006 0 0 0 6.95 0l1.71-1.71"
          />
          <line x1="8" y1="2" x2="8" y2="5" />
          <line x1="2" y1="8" x2="5" y2="8" />
          <line x1="16" y1="19" x2="16" y2="22" />
          <line x1="19" y1="16" x2="22" y2="16" />
        </svg>
      </button>
    </template>
    <template v-else>
      <div class="docx-hyperlink-popup__edit-row">
        <input
          class="docx-hyperlink-popup__input"
          :placeholder="t('hyperlinkPopup.displayTextPlaceholder')"
          v-model="editText"
          @keydown.enter.prevent="saveEdit"
          @keydown.esc="$emit('close')"
        />
      </div>
      <div class="docx-hyperlink-popup__edit-row">
        <input
          class="docx-hyperlink-popup__input"
          placeholder="https://..."
          v-model="editHref"
          @keydown.enter.prevent="saveEdit"
          @keydown.esc="$emit('close')"
        />
        <button
          class="docx-hyperlink-popup__apply"
          :disabled="!editHref.trim()"
          @click.prevent="saveEdit"
        >
          {{ t('common.apply') }}
        </button>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onBeforeUnmount, type CSSProperties } from 'vue';
import { useTranslation } from '../../i18n';

const { t } = useTranslation();

export type { HyperlinkPopupData } from './hyperlinkPopupTypes';
import type { HyperlinkPopupData } from './hyperlinkPopupTypes';

const props = defineProps<{
  data: HyperlinkPopupData | null;
  readOnly?: boolean;
}>();

const emit = defineEmits<{
  (e: 'navigate', href: string): void;
  (e: 'copy', href: string): void;
  (e: 'edit', displayText: string, href: string): void;
  (e: 'remove'): void;
  (e: 'close'): void;
}>();

const isEditing = ref(false);
const editText = ref('');
const editHref = ref('');
const popupRef = ref<HTMLDivElement | null>(null);

// Position comes from props.data.position in container coordinates. With
// position: absolute inside the pages-viewport, the browser handles scroll
// repositioning — no JS listeners needed.
const popupStyle = computed<CSSProperties>(() => ({
  left: (props.data?.position.left ?? 0) + 'px',
  top: (props.data?.position.top ?? 0) + 'px',
}));

watch(
  () => props.data?.href,
  () => {
    isEditing.value = false;
  }
);

let outsideMouseDownListener: ((e: MouseEvent) => void) | null = null;
let outsideListenerTimer: ReturnType<typeof setTimeout> | null = null;

function teardownListeners() {
  if (outsideListenerTimer) {
    clearTimeout(outsideListenerTimer);
    outsideListenerTimer = null;
  }
  if (outsideMouseDownListener) {
    document.removeEventListener('mousedown', outsideMouseDownListener);
    outsideMouseDownListener = null;
  }
}

watch(
  () => props.data,
  (data) => {
    teardownListeners();
    if (!data) return;

    // Close on click outside the popup. Defer attaching so the click that
    // opened the popup doesn't immediately close it.
    outsideMouseDownListener = (e: MouseEvent) => {
      const el = popupRef.value;
      if (el && !el.contains(e.target as Node)) {
        emit('close');
      }
    };
    outsideListenerTimer = setTimeout(() => {
      if (outsideMouseDownListener) {
        document.addEventListener('mousedown', outsideMouseDownListener);
      }
    }, 0);
  },
  { immediate: true }
);

onBeforeUnmount(teardownListeners);

function startEdit() {
  if (!props.data) return;
  editText.value = props.data.displayText;
  editHref.value = props.data.href;
  isEditing.value = true;
}

function saveEdit() {
  if (!editHref.value.trim()) return;
  emit('edit', editText.value, editHref.value);
  isEditing.value = false;
}

function onCopy() {
  if (!props.data) return;
  emit('copy', props.data.href);
  if (typeof navigator !== 'undefined' && navigator.clipboard) {
    navigator.clipboard.writeText(props.data.href).catch(() => {});
  }
}
</script>

<style scoped>
.docx-hyperlink-popup {
  position: absolute;
  z-index: 10000;
  background: #fff;
  border: 1px solid #dadce0;
  border-radius: 8px;
  box-shadow:
    0 1px 3px rgba(0, 0, 0, 0.12),
    0 4px 12px rgba(0, 0, 0, 0.08);
  padding: 8px 12px;
  display: flex;
  align-items: center;
  gap: 8px;
  max-width: 400px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  font-size: 14px;
}
.docx-hyperlink-popup--edit {
  flex-direction: column;
  align-items: stretch;
  padding: 12px;
  width: 320px;
}
.docx-hyperlink-popup__icon {
  width: 20px;
  height: 20px;
  flex-shrink: 0;
  color: #5f6368;
  display: flex;
  align-items: center;
  justify-content: center;
}
.docx-hyperlink-popup__url {
  color: #1a73e8;
  text-decoration: none;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 220px;
  font-size: 14px;
  line-height: 20px;
  cursor: pointer;
}
.docx-hyperlink-popup__sep {
  width: 1px;
  height: 20px;
  background: #dadce0;
  flex-shrink: 0;
}
.docx-hyperlink-popup__btn {
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  border: none;
  background: none;
  border-radius: 4px;
  cursor: pointer;
  color: #5f6368;
  padding: 0;
  flex-shrink: 0;
}
.docx-hyperlink-popup__btn:hover {
  background: #f1f3f4;
}
.docx-hyperlink-popup__edit-row {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
}
.docx-hyperlink-popup__edit-row:last-child {
  margin-bottom: 0;
}
.docx-hyperlink-popup__input {
  flex: 1;
  padding: 6px 8px;
  border: 1px solid #dadce0;
  border-radius: 4px;
  font-size: 14px;
  outline: none;
  line-height: 20px;
}
.docx-hyperlink-popup__input:focus {
  border-color: #1a73e8;
}
.docx-hyperlink-popup__apply {
  color: #1a73e8;
  font-weight: 600;
  font-size: 14px;
  border: none;
  background: none;
  cursor: pointer;
  padding: 6px 12px;
  border-radius: 4px;
  flex-shrink: 0;
}
.docx-hyperlink-popup__apply:disabled {
  color: #80868b;
  cursor: not-allowed;
}
</style>
